- name: Install mysql component
  hosts: mysql
  tasks:
   - name: Disable old repos of mysql
     ansible.builtin.shell: yum module disable mysql
   - name: copy mysql repo into yum.repos.d
     ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo
   - name: Install mysql package
     ansible.builtin.yum:
      name: mysql-community-server
      state: installed
      update_cache: yes
   - name: start and enable mysql
     ansible.builtin.service:
      name: mysqld
      state: started
      enabled: true 
   - name: setup mysql root password
     ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1