- name: Install rabbitmq component
  hosts: robbitmq
  become: yes
  tasks:
   - name: configure rabbitmq yum repos
     ansible.builtin.shell: "{{item}}"
     loop:
      - "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
      - "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"
   - name: Install rabbitmq package
     ansible.builtin.yum:
      name: rabbitmq-server
      state: installed
   - name: Start and enable rabbitmq
     ansible.builtin.service:
      name: rabbitmq
      state: started
      enable: true
   - name: create rabbitmq user
     ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123
   - name: setup permissions
     ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
      