- name: Install user component
  hosts: user
  become: yes
  tasks:
   - name: setup NPM source
     ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
   - name: Install NodeJs
     ansible.builtin.yum:
      name: nodejs
      state: installed
      disable_gpg_check: true
      update_cache: yes
   - name: check if roboshop useris exist or not 
     ansible.builtin.command: id roboshop 
     register: output
     ignore_errors: true
   - name: Print the user output
     ansible.builtin.debug:
      msg: "output is: {{output}}"
   - name: Print the exit status
     ansible.builtin.debug:
      msg: "output is: {{output.rc}}"
   - name: create roboshop user
     ansible.builtin.user:
      name: roboshop 
     when: output.rc != 0
   - name: check /app directory is exists or not
     ansible.builtin.stat:
      path: /app
     register: directory
   - name: print the directory output
     ansible.builtin.debug:
      msg: "output is:{{directory}}"
   - name: if app directory exists,create /app directory
     ansible.builtin.file:
      name: /app
      state: directory
     when: directory.stat.exists == False
   - name: download user application code into /tmp
     ansible.builtin.get_url:
      url: "https://roboshop-builds.s3.amazonaws.com/user.zip"
      dest: /tmp
   - name: extract user application code into /app folder
     ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes
   - name: Install dependencies
     ansible.builtin.shell: npm install
     args:
      chdir: /app
   - name: copy user service
     ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service
   - name: reload daemon
     ansible.builtin.systemd:
      daemon_reload: true
   - name: start and enable service
     ansible.builtin.service:
      name: user
      state: started
      enabled: true
   - name: copy mongodb repo into yum.repos.d
     ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo
   - name: install mongodb client package
     ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed
      update_cache: yes
   - name: load user data
     ansible.builtin.shell: mongo --host mongodb.sivadevops.website </app/schema/user.js
   - name: restart user service
     ansible.builtin.service:
      name: user
      state: restarted